blank_issues_enabled: false
contact_links:
  - name: 🥶 Repository Frozen
    url: https://github.com/samtstern/github-sandbox/pulls
    about: This repository is no longer accepting new issues. If you want to help us fix an existing issue, send a Pull Request!
